[package]
name = "martin"
version = "0.5.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]
edition = "2018"

[lib]
name = "martin"
path = "src/lib.rs"

[[bin]]
name = "martin"
path = "src/bin/main.rs"

[dependencies]
actix = "0.12"
actix-cors = "0.5.4"
actix-rt = "1.1"
actix-web = "3.3.2"
docopt = "1"
env_logger = "0.9"
itertools = "0.10"
log = "0.4"
native-tls = "0.2"
num_cpus = "1.13"
postgres = { version = "0.19.1", features = ["with-time-0_2", "with-uuid-0_8", "with-serde_json-1"] }
postgres-native-tls = "0.5.0"
postgres-protocol = "0.6.1"
r2d2 = "0.8"
r2d2_postgres = "0.18"
semver = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tilejson = "0.2"

[dev-dependencies]
criterion = "0.3"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "prepush-hook", "run-cargo-fmt", "run-cargo-clippy", "run-cargo-test"]

[[bench]]
name = "server"
harness = false
